# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/Users/marin/Documents/Ma2/ACA/AdvComparch

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/Users/marin/Documents/Ma2/ACA/AdvComparch

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/marin/Documents/Ma2/ACA/AdvComparch/CMakeFiles /mnt/c/Users/marin/Documents/Ma2/ACA/AdvComparch//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/marin/Documents/Ma2/ACA/AdvComparch/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ParserTest

# Build rule for target.
ParserTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ParserTest
.PHONY : ParserTest

# fast build rule for target.
ParserTest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParserTest.dir/build.make CMakeFiles/ParserTest.dir/build
.PHONY : ParserTest/fast

ParserTest.o: ParserTest.c.o
.PHONY : ParserTest.o

# target to build an object file
ParserTest.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParserTest.dir/build.make CMakeFiles/ParserTest.dir/ParserTest.c.o
.PHONY : ParserTest.c.o

ParserTest.i: ParserTest.c.i
.PHONY : ParserTest.i

# target to preprocess a source file
ParserTest.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParserTest.dir/build.make CMakeFiles/ParserTest.dir/ParserTest.c.i
.PHONY : ParserTest.c.i

ParserTest.s: ParserTest.c.s
.PHONY : ParserTest.s

# target to generate assembly for a file
ParserTest.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParserTest.dir/build.make CMakeFiles/ParserTest.dir/ParserTest.c.s
.PHONY : ParserTest.c.s

cJSON.o: cJSON.c.o
.PHONY : cJSON.o

# target to build an object file
cJSON.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParserTest.dir/build.make CMakeFiles/ParserTest.dir/cJSON.c.o
.PHONY : cJSON.c.o

cJSON.i: cJSON.c.i
.PHONY : cJSON.i

# target to preprocess a source file
cJSON.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParserTest.dir/build.make CMakeFiles/ParserTest.dir/cJSON.c.i
.PHONY : cJSON.c.i

cJSON.s: cJSON.c.s
.PHONY : cJSON.s

# target to generate assembly for a file
cJSON.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParserTest.dir/build.make CMakeFiles/ParserTest.dir/cJSON.c.s
.PHONY : cJSON.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... ParserTest"
	@echo "... ParserTest.o"
	@echo "... ParserTest.i"
	@echo "... ParserTest.s"
	@echo "... cJSON.o"
	@echo "... cJSON.i"
	@echo "... cJSON.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

